name: Swift

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: spm
      run: fastlane run spm
    - name: Run tests
      run: bundle exec fastlane testLine
