name: Swift

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    run-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: bundle exec fastlane testLine
